In [3]:
her = {0: 'her', 1: 'reer', 4: 'reuuu'}

In [7]:
her[3] = 'ferrr'

In [12]:
def class_mapping(label, numb_class):
    y_train = []
    for x in label:
        assert int(x) < numb_class
        y_train.append([int(i==int(x)) for i in range(numb_class)])
        
    return y_train

In [14]:
print(class_mapping('11', 3))
print(class_mapping('0101', 3))
print(class_mapping('02', 3))

[[0, 1, 0], [0, 1, 0]]
[[1, 0, 0], [0, 1, 0], [1, 0, 0], [0, 1, 0]]
[[1, 0, 0], [0, 0, 1]]


In [19]:
def tokenisation(word, num_token = 3):
    x_train = []
    for x in word:
        if x == 'a':
            x_train.append(0)
        elif x == 'b':
            x_train.append(1)
        else:
            x_train.append(2)
    
    return x_train

A =tokenisation('aabbz')

In [21]:
print(A)

[0, 0, 1, 1, 2]


In [22]:
def masking(word, pad_char = 'z'):
    return [x!=pad_char for x in word]

masking('abbz')

[True, True, True, False]

In [23]:
from utils import class_mapping, tokenization, masking
import numpy as np

In [24]:
max_length = 4
corpus = ['ba', 'b', 'a', 'baa', 'a', 'baaa', 'aa', 'b', 'abaa', 'abb', 'bb']
labels = ['11', '1', '1', '110', '1', '1100', '10', '1', '1010', '101', '11']
corpus_ = ["e"+x+"z"*(max_length-len(x)) for x in corpus]
labels_ = ["0"+x+"2"*(max_length - len(x)) for x in labels]
states = []

x_train = np.array([tokenization(x) for x in corpus_])
y_train = np.array([class_mapping(x) for x in labels_])
mask = np.array([masking(x) for x in corpus_])

In [27]:
#print(x_train)
print(mask)

[[ True  True  True False False]
 [ True  True False False False]
 [ True  True False False False]
 [ True  True  True  True False]
 [ True  True False False False]
 [ True  True  True  True  True]
 [ True  True  True False False]
 [ True  True False False False]
 [ True  True  True  True  True]
 [ True  True  True  True False]
 [ True  True  True False False]]


In [29]:
import tensorflow as tf

In [33]:
labels_ = [[[1,0,0], [0,1,0], [1,0,0]], [[0,0,1],[0,1,0], [0,1,0]]]
logits_ = [[[0.91,0.08,0.01], [0.2,0.6,0.2], [0.75,0.05,0.2]], [[0.33,0.1,0.57],[0.8,0.1,0.1], [0.04,0.9,0.06]]]
labels = tf.convert_to_tensor(labels_, dtype=tf.float32)
logits = tf.convert_to_tensor(logits_, dtype=tf.float32)

In [34]:
predictions_ = tf.equal(tf.argmax(logits, -1), tf.argmax(labels, -1))
predictions_

<tf.Tensor: shape=(2, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True, False,  True]])>

In [40]:
accuracy = tf.reduce_mean(tf.cast(predictions_, tf.float32))
accuracy.numpy()

0.8333333

In [1]:
ter = (2,3,4)

In [13]:
ter[2]

4

In [16]:
class Mealy(object):

    def __init__(self, root, nodes, arcs):
        # nodes = [0,1,2,...]
        # arcs = [(0,a,1,1), ...]

        self.root =  root
        self.node = nodes
        self.transitions = arcs

    """def label(self, word):
        node = self.root
        label = []
        for x in word:
            label.append(self.states[node.children[i][1]])"""
    
    def output(self, initial_state, input_char):
        for x in self.transitions:
            if x[0] == initial_state and x[1] ==  input_char:
                return (x[2], x[3])
        return None

    def return_outputs(self, word):
        output = []
        for i in range(len(word)):
            if i == 0:
                output.append(self.root)
            else:
                output.append(self.output(output[i-1], word[i])[1])
        return output
    
    def return_states(self, word):
        idx = []
        for i in range(len(word)):
            if i == 0:
                idx.append(self.root)
            else:
                idx.append(self.output(idx[i-1], word[i])[0])
        return idx

In [17]:
class node(object):
    
    def __init__(self, children):
        self.children = children
        
node = [0,1,2,3,4]
arcs = [(0,'a',1,1), (0,'b',0,2), (1,'a',0,3), (2,'b',1,4)]
m = Mealy(0, node, arcs)

o = m.return_states('eaa')
print(o)

(1, 1)
(0, 3)
[0, 1, 0]


In [19]:
import tensorflow as tf

a = tf.constant([[1, 2], [3, 4]])                 
b = tf.add(a, 1)

a.numpy()

array([[1, 2],
       [3, 4]])

In [8]:
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

x = np.array([[2,3,4],
     [2.6, 1.3, 2.8],
     [8.1, 7.2, 7.5]])

y = np.array([1, 0, 1])

model2 = Sequential()
model2.add(Dense(units=2, input_dim=3, kernel_initializer='normal', activation=None))
model2.add(Dense(1, kernel_initializer='normal'))
model2.compile(loss='mean_squared_error', optimizer='adam', metrics='accuracy')
print(model2.summary())

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 2)                 8         
                                                                 
 dense_7 (Dense)             (None, 1)                 3         
                                                                 
Total params: 11
Trainable params: 11
Non-trainable params: 0
_________________________________________________________________
None


In [9]:
model2.fit(x, y, 1, 3)

Epoch 1/3
3/3 [==============================] - 4s 48ms/step - loss: 0.6775 - accuracy: 0.3333
Epoch 2/3
3/3 [==============================] - 0s 5ms/step - loss: 0.6713 - accuracy: 0.3333
Epoch 3/3
3/3 [==============================] - 0s 17ms/step - loss: 0.6657 - accuracy: 0.3333


In [16]:

output_layers = ['output1', 'output2']
model2.metrics_tensors += [layer.output for layer in model.layers if layer.name in output_layers]


AttributeError: 'Sequential' object has no attribute 'metrics_tensors'

In [ ]:
import numpy as np
import matplotlib as plt

id = range(0,9)
x = [i+2 for i in id]
y = [10,10,8,10,3,3,6,10,1,6]
fig,ax = plt.subplots(figsize=(12,6))
ax.bar(x, y, 0.4)
ax.set_xticks(x)
ax.set_xlabel("Nombre d'états")
ax.set_ylabel("# machines équivalentes")
ax.axhline(y=10,color='red',ls='-')